:concurrency: 3
:timeout: 60
:verbose: true
:queues:
  - critical
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge

:scheduler:
  :schedule:
    abandoned_carts_job:
      cron: '*/15 * * * * *'   # Runs once per minute
      class: "MarkCartAsAbandonedJob"
